### PR TITLE
update pkgs for twistlock

### PR DESCRIPTION
**Pull request by bluzarraga**
I am a little more wary about this change compared to the other ones I have opened. The client_golang package went from 1.1.0 to 1.11.1 changing several other packages along with it. May need to do some testing with this one to make sure nothing is broken.

### CODE REVIEW

**Comment by bluzarraga** [comment]
not sure why this is failing, after updating the package go-logr, the build comepleted and I was able to deploy the image and successfully test against the SERT regression tests. This pr should be good to go

**Comment by bluzarraga** [comment]
problem lies in updating the k8s.io/client-go package. We're currently at 0.18.6 (which is really old, latest is 0.26.1.  We need at least 0.20.0-alpha.2+. I will try to find a happy medium where I can update this pkg to and not have to do intense refactors but due to the age and the importance of this package, it might be difficult.

**Comment by bluzarraga** [comment]
Not sure what the difference is between the checks now but I will try building this image and running the SERT regression tests. It previously passed so I expect it to pass again.

**Comment by Daniel-Fan** [comment]
This might relate to recently golang version bump from 1.9.4 to 1.20.0
https://github.com/IBM/ibm-namespace-scope-operator/commit/c3389decca48724934c5e2b57980e71d5881c00d

**Comment by bluzarraga** [comment]
All checks passed, regression test passed as well. This PR is good to go.

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Pull request merged**
