### PR TITLE
reduce permission for future NSS operator

### PR DESCRIPTION
**Pull request by Daniel-Fan**
Signed-off-by: YuChen <yuchen.shen@mail.utoronto.ca>

### CODE REVIEW

**Comment by bitscuit** [comment]
Any steps on how to test?

**Comment by YCShen1010** [comment]
@bitscuit This is to further reduce permission on NSS operator. NSS operator-restricted will only have namespace permission on NSS CR out of the box.
User need to manually grant NSS operator permission to operator NS.

Test step:

1. Apply New CatalogSource for NSS operator in cluster (with the image built by this pr)
2. Install NSS operator in the same namespace as CommonService
3. Found error msg in pod complaining about failed to list resources
```
E0203 15:44:51.678555 1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:cs-1:ibm-namespace-scope-operator" cannot list resource "configmaps" in API group "" in the namespace "nss-permission"
```
4. [Run script](https://github.com/IBM/ibm-namespace-scope-operator#authorization-and-permissions) to manually create namespace admin role for NSS operator

**Review by YCShen1010 — APPROVED** [review]
/lgtm

**Comment by pgodowski** [comment]
This change ended up with no RBAC for NSS-restricted even in its namespace. Specifically, it does not have RBAC for Roles/RoleBindings/ConfigMaps

**Comment by Daniel-Fan** [comment]
Originally we would like to avoid restricted NSS operator automatically gaining full cluster admin permission when it is installed in All Namespaces Mode.

But it indeed introduces some fallback that we need to manually grant permission for restricted NSS operator in its own namespace.
Revert the changes in PR: https://github.com/IBM/ibm-namespace-scope-operator/pull/218

**Pull request merged**
